### ISSUE TITLE
Safe to update to libsvtav1 3.0.0?

### ISSUE THREAD

**Issue by kz26** [BtbN/FFmpeg-Builds#461]
Per this [latest ffmpeg commit from 2025-02-22](https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/d1ed5c06e3edc5f2b5f3664c80121fa55b0baa95), building with libsvtav1 should no longer be broken. I just did a linux64 gpl ffmpeg master build using your pipeline (with libsvtav1 [3.0.0](https://gitlab.com/AOMediaCodec/SVT-AV1/-/commit/442fc31a1cc12be618a9e112d3b41deb8fb398ab)) and libsvtav1 encoding seems to work fine.

**Comment by BtbN** [comment]
It'll be broken for everything but master.
If that's not fixed by the next time I do a round of dependency updates, I'll have to pick between staying on an old version or dropping svt-av1 support for everything but master.

**Comment by hwangsihu** [comment]
master? Did you mean FFmpeg master?

**Comment by avtneyney** [comment]
Fixed in the latest [7.1.1 release tag](https://git.ffmpeg.org/gitweb/ffmpeg.git/tag/refs/tags/n7.1.1).

**Comment by BtbN** [comment]
Not sure where you're getting that from.
Clearly still broken on the 7.1 branch: https://github.com/BtbN/FFmpeg-Builds/actions/runs/13638909182/job/38135612244#step:5:3430

**Comment by kamild1996** [comment]
I'm guessing that's why neither the 2025-03-17-git-5b9356f18e and release 7.1.1 builds have the SVT-AV1 encoder in them?

**Comment by BtbN** [comment]
Only master and all future releases of ffmpeg will have it (until they pull a stunt like this again), since SVT-AV1 makes no effort to maintain old versions, that's the only viable option to keep it.

**Comment by BtbN** [comment]
"2025-03-17-git-5b9356f18e" sounds like it's a master build though? So it should have it.

**Comment by kamild1996** [comment]
That one is on me, I apologize, I forgot SVT-AV1 does not come in the essentials package but in the full one...

**Comment by BtbN** [comment]
I don't have any such variants though. So you must be confusing something.

**Comment by kamild1996** [comment]
...yes I am, confusing builds, let's just forget about it...
